services:
  rordle-db:
    container_name: rordle-db
    image: postgres:17
    restart: unless-stopped
    env_file: ./api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rordle-api:
    container_name: rordle-api
    build: ./apps/api
    volumes:
      - ./apps/api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  rordle-app:
    container_name: rordle-app
    build: ./apps/web
    volumes:
      - ./apps/web:/app
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: